[package]
name = "delete-git-branches"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.14.2"
thiserror = "1.0.30"
crossterm = "0.23.1"
chrono = "0.4.2"
